### ISSUE TITLE
Mkdir permission error in low permission environment

### ISSUE THREAD

**Issue by shan-mx** [dotenvx/dotenvx#315]
It seems that dotenvx attempts to mkdir in current user directory to store configuration. However, it will lead to error in low permission ec2 or lambda environment.

EC2 Logs:
```
[ec2-user@ip-172-31-2-10 dot3]$ ./dotenvx help
pkg/prelude/bootstrap.js:1864
throw error;
^
Error: EACCES: permission denied, mkdir '/home/ec2-user/.config/dotenvx'
at Object.mkdirSync (node:fs:1349:3)
at Object.mkdirSync (pkg/prelude/bootstrap.js:1631:33)
at Conf._ensureDirectory (/snapshot/dotenvx/node_modules/conf/dist/source/index.js:358:12)
at Conf.get store [as store] (/snapshot/dotenvx/node_modules/conf/dist/source/index.js:284:22)
at new Conf (/snapshot/dotenvx/node_modules/conf/dist/source/index.js:131:32)
at Object.<anonymous> (/snapshot/dotenvx/src/shared/store.js:39:19)
at Module._compile (node:internal/modules/cjs/loader:1105:14)
at Module._compile (pkg/prelude/bootstrap.js:1925:32)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
at Module.load (node:internal/modules/cjs/loader:981:32) {
errno: -13,
syscall: 'mkdir',
code: 'EACCES',
path: '/home/ec2-user/.config/dotenvx'
}

[ec2-user@ip-172-31-2-10 dot3]$ sudo ./dotenvx help
Usage: @dotenvx/dotenvx [options] [command] [command] [args...]

a better dotenv–from the creator of `dotenv`

Arguments:
command dynamic command
args dynamic command arguments

Options:
-l, --log-level <level> set log level (default: "info")
```

Lambda Logs:
<img width="613" alt="image" src="https://github.com/user-attachments/assets/11015095-31a6-4604-83f6-e49f9cf06631">

FYI, the only writable directory is /tmp in lambda execution environment, and some lambda deployments require the image to be able to run in read-only file system. I'd appreciate it if dotenvx can catch the error when writing to the config.

**Comment by shan-mx** [comment]
The config is defined here:
https://github.com/dotenvx/dotenvx/blob/86f7b9e874a0d972fac3c08967004afdac8ce67a/src/shared/store.js#L39

**Comment by sdg9670** [comment]
How can I give permission for this error in container?

**Comment by motdotla** [comment]
effort started here: https://github.com/dotenvx/dotenvx/pull/323

**Comment by motdotla** [comment]
releasing as `1.7.0`. closing this, but re-comment and I'll re-open - if any issue still.
